### ISSUE TITLE
Compatibility issue with Tech Reborn

### ISSUE THREAD

**Issue by KillReallll** [AViewFromTheTop/SimpleCopperPipesMC#46]
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'techreborn' at 'techreborn.TechRebornClient'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at knot//techreborn.TechRebornClient.onInitializeClient(TechRebornClient.java:150)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3300.method_14486(net.minecraft.class_2960)" because the return value of "net.minecraft.class_310.method_1478()" is null
	at knot//net.minecraft.class_437.wrapOperation$bfa000$frozenlib$multiplePanoramas(class_437.java:2220)
	at knot//net.minecraft.class_437.<clinit>(class_437.java:61)
	... 8 more

Fabric API 0.107. Minecraft version 1.21.1

**Comment by AViewFromTheTop** [comment]
Is this issue fixed if you install the latest version of FrozenLib? If so, I’ll update the mod to include that one instead.

**Comment by AViewFromTheTop** [comment]
Should be fixed with the 2.0 hotfix just released for 1.21/1.21.1.
